var myString;
var myNum;
var myBool;
var myVar;
/* let strArr: string[];
let numArr: number[];
let boolArr: boolean[]; */
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello World';
myNum = 1;
myBool = true;
myVar = false;
strArr = ['Hello', 'World', 'Array'];
numArr = [1, 2, 3];
boolArr = [true, false, false];
strNumTuple = ['hello', 1];
var myVoid = null;
var myNull = null;
var myUndefined = null;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(myVoid);
